print('>>>>>>>>>>>>>>>>>>>>>>>>>>>>>')
print  ( '>>>>>>>>>>>>>>>>>>>>>>>>>>>>>')
print ('>>>|) |``| |`` |,,| |`` `|>>>')
print ('>>>|\ |  | ``|    | ```| |>>>')
print ('>>>| \|,,| ,,|    | ,,,| |>>>')
print('>>>>>>>>>>>>>>>>>>>>>>>>>>>>>')
print('>>>>>>>>>>>>>>>>>>>>>>>>>>>>>')
print (' ')
print (' ')
print (' ')
print ('#nama   =rusadi')
print ('#tools  =R05461')
print ('#channel= hackers termux')
print (' Subcribe guys ')
print ('')
print ('')
print ('WARNING..')
print ('')
print ('')
print ('selagi menjalankan tools ini tolong BOKEPnya di close dulu ya boos')
print ('wkwkckk')